### ISSUE TITLE
Docker Autobuilds are disabled

### ISSUE THREAD

**Issue by StrikerRUS** [guolinke/lightgbm-ci-docker#18]
@guolinke I got the following e-mail:

---

Action Required: Upgrade to continue using Docker Autobuilds
===

Hi there!

As you may remember, on June 7, 2021 we [announced](https://www.docker.com/blog/changes-to-docker-hub-autobuilds) the end of Autobuilds for all free accounts and starting on Monday, July 26, 2021 all Autobuilds associated with a free account will be disabled and stop working.

If you would like to ensure your currently setup Autobuilds continue to function beyond the July 26th shutoff date please upgrade to a [Pro or Team plan](https://www.docker.com/pricing).

Thanks,
The Docker Team

---

I think we can continue using Docker Hub for this repo but have to trigger all builds (for PRs and `master` branch) manually. Given the frequency of commits in this repo, I don't think this will be hard.

**Comment by guolinke** [comment]
Thank you, @StrikerRUS , it is fine for me

**Comment by StrikerRUS** [comment]
OK, I'll test manual builds after 26th.

**Comment by StrikerRUS** [comment]
@guolinke Seems that now we are not allowed to perform **any** builds at Docker Hub: I can't find how to trigger a build manually. We now have to build images locally and then push them to Docker Hub.

I'd like to add a GitHub Action Workflow which will do that for us.
https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-docker-hub
Could you please either add your Docker Hub credentials to GitHub Secrets (`secrets.DOCKER_USERNAME`, `secrets.DOCKER_PASSWORD` as in example) or allow me to access this repo settings - I'll add mine.

Also, please check Slack DM.

**Comment by StrikerRUS** [comment]
Kindly ping @guolinke

**Comment by guolinke** [comment]
![image](https://user-images.githubusercontent.com/16040950/130647307-8f584001-4a17-4632-a61d-82dad212a53b.png)
I think I already add you. But it seems you cannot add Secrets?

**Comment by guolinke** [comment]
added DOCKER_USERNAME and DOCKER_PASSWORD
![image](https://user-images.githubusercontent.com/16040950/130647753-adee6483-8406-4708-9b37-136398684b8c.png)

**Comment by StrikerRUS** [comment]
@guolinke Thanks a lot!

> But it seems you cannot add Secrets?

Yeah, here is what I see when open the repo (no `Settings` tab):

![image](https://user-images.githubusercontent.com/25141164/130786409-f2be6170-43ca-41ba-9ab5-ed859123d194.png)

Compared with LightGBM repo:

![image](https://user-images.githubusercontent.com/25141164/130786518-515a874e-0cf2-4e0a-89a9-f81f7e766123.png)
